cask_args appdir: '/Applications'

tap 'homebrew/cask-cask'
tap 'homebrew/bundle'

brew 'go'
brew 'imagemagick'
brew 'node'
brew 'unrar'
brew 'wget'
brew 'tmux'
brew 'vim'
brew 'watch'
brew 'qt'
brew 'zsh'
brew 'python'

cask '1password'
cask 'atom'
cask 'firefox'
cask 'google-chrome'
cask 'slack'
cask 'vlc'
cask 'xquartz'
cask 'spotify'
cask 'whatsapp'
cask 'bettertouchtool'
cask 'karabiner-elements'
cask 'pycharm'
cask 'rstudio'
cask 'docker'
