cask_args appdir: '/Applications'

tap 'homebrew/cask-cask'
tap 'homebrew/bundle'
tap 'adoptopenjdk/openjdk'
tap 'microsoft/mssql-release'

brew 'azure-cli'
brew 'mssql-tools'
brew 'openjdk@11'
brew 'pyenv'
brew 'pyenv-virtualenv'

cask 'adoptopenjdk8'
cask 'pycharm-ce'
cask 'postman'
cask 'azure-data-studio'
